#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

if [ ! -e $DIR/$1 ]
then
    echo "Can't link $DIR/$1 to your home directory because it doesn't exist."
    exit 1
fi

if [ -L $HOME/$1 ]
then
    echo "$HOME/$1 exists and is a symbolic link."
    echo "Run \`mv $HOME/$1 $HOME/$1.bak\`"
    exit 2
fi

echo "creating symlink"
if (( $(ln -s $DIR/$1 $HOME/$1) ))
then
    echo "Creating symlink failed."
    exit 3
fi

echo "Symlink created:"
ls -lA $HOME/$1


exit 0

