## Starship Config
## Docs: https://starship.rs/config/
##
## ## Color Palette
##
## All instructions can be found at [draculatheme.com](https://draculatheme.com/).
##
## | Palette      | Hex       | RGB           | HSL             | ![Color Picker Boxes](https://draculatheme.com/static/img/color-boxes/eyedropper.png)   |
## | ------------ | --------- | ------------- | --------------- | --------------------------------------------------------------------------------------- |
## | Background   | `#282a36` | `40 42 54`    | `231° 15% 18%`  | ![Background Color](https://draculatheme.com/static/img/color-boxes/background.png)     |
## | Current Line | `#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Current Line Color](https://draculatheme.com/static/img/color-boxes/current_line.png) |
## | Selection    | `#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Selection Color](https://draculatheme.com/static/img/color-boxes/selection.png)       |
## | Foreground   | `#f8f8f2` | `248 248 242` | `60° 30% 96%`   | ![Foreground Color](https://draculatheme.com/static/img/color-boxes/foreground.png)     |
## | Comment      | `#6272a4` | `98 114 164`  | `225° 27% 51%`  | ![Comment Color](https://draculatheme.com/static/img/color-boxes/comment.png)           |
## | Cyan         | `#8be9fd` | `139 233 253` | `191° 97% 77%`  | ![Cyan Color](https://draculatheme.com/static/img/color-boxes/cyan.png)                 |
## | Green        | `#50fa7b` | `80 250 123`  | `135° 94% 65%`  | ![Green Color](https://draculatheme.com/static/img/color-boxes/green.png)               |
## | Orange       | `#ffb86c` | `255 184 108` | `31° 100% 71%`  | ![Orange Color](https://draculatheme.com/static/img/color-boxes/orange.png)             |
## | Pink         | `#ff79c6` | `255 121 198` | `326° 100% 74%` | ![Pink Color](https://draculatheme.com/static/img/color-boxes/pink.png)                 |
## | Purple       | `#bd93f9` | `189 147 249` | `265° 89% 78%`  | ![Purple Color](https://draculatheme.com/static/img/color-boxes/purple.png)             |
## | Red          | `#ff5555` | `255 85 85`   | `0° 100% 67%`   | ![Red Color](https://draculatheme.com/static/img/color-boxes/red.png)                   |
## | Yellow       | `#f1fa8c` | `241 250 140` | `65° 92% 76%`   | ![Yellow Color](https://draculatheme.com/static/img/color-boxes/yellow.png)             |
##
## For more details about how to apply these different colors to represent different code symbols, please see the [Dracula Specification](https://spec.draculatheme.com).

format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$ruby\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

right_format = """$cmd_duration"""
command_timeout = 2000

[character]
success_symbol = "[|>](bold bright-blue)"
error_symbol = "[|>](bold blue)"

[aws]
disabled = true

[cmd_duration]
style = "bold #ffb86c"
format =" [$duration]($style)"
min_time = 10_000
show_notifications = true
min_time_to_notify = 120_000

[directory]
style = "italic blue"

[docker_context]
disabled = true

[elixir]
style = "blue"
symbol = " "
format = '[with](italic) [$symbol($version \(OTP $otp_version\) )]($style)'

[golang]
symbol = " "

[terraform]
symbol = '󱁢 '
disabled = true

[time]
style = "white"
format = "[$time]($style) "
time_format = "%H:%M"
disabled = false

[git_branch]
format = '([ $branch]($style)) '
symbol = " "
style = "bold cyan"
truncation_length = 24

[git_status]
style = "white"
format = '([$all_status$ahead_behind]($style) )'
ahead = " [+${count}](bold green)"
behind = " [-${count}](bold red)"
diverged = "[+${ahead_count}](bold green) [-${behind_count}](bold red)"
modified = "[M](bold red)"
stashed = "[∼∽](bold yellow)"
staged = "[S](bold green)"
renamed = "[R](bold green)"
deleted = "[D](bold red)"
conflicted = "[U](bold red)"

[git_state]
style = "bold bright-yellow"
format = '[$state]($style italic)[( $progress_current/$progress_total)]($style) '

[nodejs]
format = "[$symbol($version )]($style)"

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[package]
disabled = true
symbol = "  "
