[env]
_.file = '.env'

[tools]
nodejs = '19.8.1'
ruby = 'latest'
elixir = '1.15.6-otp-26'
erlang = '26.1.1'
python = '3.7.2'
elm = '0.19.1'
terraform = '0.12.29'
yarn = '1.9.4'
golang = '1.22.3'
bun = '1.0.2'

